[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ec-mos-toolkits"
version = "0.1.0.dev0"
description = "A toolkit for electrochemistry of aqueous metal oxide semiconductor (MOS) interfaces"
readme = "README.md"
requires-python = ">=3.8"

authors = [
  { name = "Zi-Heng Gong", email = "cyclones-x@outlook.com" }
]

license = "MIT"

dependencies = [
  "numpy<=1.24",
  "scipy",
  "ase",
  "matplotlib",
  "MDAnalysis",
]

[tool.setuptools.packages.find]
include = ["ec_mos_toolkits*"]
exclude = ["manual*", "docs*", "tests*"]

[project.urls]
Homepage = "https://github.com/Cyclones-X/ec-mos-toolkits"
